# Generated by Django 2.0.5 on 2018-05-31 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First', models.CharField(default='', max_length=50, null=True)),
                ('Last', models.CharField(default='', max_length=50, null=True)),
            ],
        ),
    ]
